# Form implementation generated from reading ui file 'UI\addEditCoffeeForm.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddEditCoffeeForm(object):
    def setupUi(self, AddEditCoffeeForm):
        AddEditCoffeeForm.setObjectName("AddEditCoffeeForm")
        AddEditCoffeeForm.resize(560, 410)
        self.verticalLayout = QtWidgets.QVBoxLayout(AddEditCoffeeForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.sort_name_label = QtWidgets.QLabel(parent=AddEditCoffeeForm)
        self.sort_name_label.setObjectName("sort_name_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.sort_name_label)
        self.sort_name_edit = QtWidgets.QLineEdit(parent=AddEditCoffeeForm)
        self.sort_name_edit.setObjectName("sort_name_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.sort_name_edit)
        self.roast_level_label = QtWidgets.QLabel(parent=AddEditCoffeeForm)
        self.roast_level_label.setObjectName("roast_level_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.roast_level_label)
        self.roast_level_edit = QtWidgets.QLineEdit(parent=AddEditCoffeeForm)
        self.roast_level_edit.setObjectName("roast_level_edit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.roast_level_edit)
        self.is_ground_label = QtWidgets.QLabel(parent=AddEditCoffeeForm)
        self.is_ground_label.setObjectName("is_ground_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.is_ground_label)
        self.is_ground_combo = QtWidgets.QComboBox(parent=AddEditCoffeeForm)
        self.is_ground_combo.setObjectName("is_ground_combo")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.is_ground_combo)
        self.taste_label = QtWidgets.QLabel(parent=AddEditCoffeeForm)
        self.taste_label.setObjectName("taste_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.taste_label)
        self.taste_description_edit = QtWidgets.QLineEdit(parent=AddEditCoffeeForm)
        self.taste_description_edit.setObjectName("taste_description_edit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.taste_description_edit)
        self.price_label = QtWidgets.QLabel(parent=AddEditCoffeeForm)
        self.price_label.setObjectName("price_label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.price_label)
        self.price_spin = QtWidgets.QDoubleSpinBox(parent=AddEditCoffeeForm)
        self.price_spin.setDecimals(2)
        self.price_spin.setMaximum(1000000.0)
        self.price_spin.setObjectName("price_spin")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.price_spin)
        self.volume_label = QtWidgets.QLabel(parent=AddEditCoffeeForm)
        self.volume_label.setObjectName("volume_label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.volume_label)
        self.package_volume_spin = QtWidgets.QSpinBox(parent=AddEditCoffeeForm)
        self.package_volume_spin.setMinimum(1)
        self.package_volume_spin.setMaximum(100000)
        self.package_volume_spin.setObjectName("package_volume_spin")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.package_volume_spin)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonsLayout = QtWidgets.QHBoxLayout()
        self.buttonsLayout.setObjectName("buttonsLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttonsLayout.addItem(spacerItem)
        self.save_button = QtWidgets.QPushButton(parent=AddEditCoffeeForm)
        self.save_button.setObjectName("save_button")
        self.buttonsLayout.addWidget(self.save_button)
        self.cancel_button = QtWidgets.QPushButton(parent=AddEditCoffeeForm)
        self.cancel_button.setObjectName("cancel_button")
        self.buttonsLayout.addWidget(self.cancel_button)
        self.verticalLayout.addLayout(self.buttonsLayout)

        self.retranslateUi(AddEditCoffeeForm)
        QtCore.QMetaObject.connectSlotsByName(AddEditCoffeeForm)

    def retranslateUi(self, AddEditCoffeeForm):
        _translate = QtCore.QCoreApplication.translate
        AddEditCoffeeForm.setWindowTitle(_translate("AddEditCoffeeForm", "Добавить / Редактировать кофе"))
        self.sort_name_label.setText(_translate("AddEditCoffeeForm", "Название сорта"))
        self.roast_level_label.setText(_translate("AddEditCoffeeForm", "Степень обжарки"))
        self.is_ground_label.setText(_translate("AddEditCoffeeForm", "Молотый/в зернах"))
        self.taste_label.setText(_translate("AddEditCoffeeForm", "Описание вкуса"))
        self.price_label.setText(_translate("AddEditCoffeeForm", "Цена"))
        self.volume_label.setText(_translate("AddEditCoffeeForm", "Объем упаковки"))
        self.save_button.setText(_translate("AddEditCoffeeForm", "Сохранить"))
        self.cancel_button.setText(_translate("AddEditCoffeeForm", "Отмена"))
