# Form implementation generated from reading ui file 'UI\main.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(980, 620)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.title_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.title_label.setStyleSheet("font-size: 20px; font-weight: 700;")
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)
        self.coffee_table = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.coffee_table.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.coffee_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.coffee_table.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.coffee_table.setAlternatingRowColors(True)
        self.coffee_table.setObjectName("coffee_table")
        self.coffee_table.setColumnCount(0)
        self.coffee_table.setRowCount(0)
        self.verticalLayout.addWidget(self.coffee_table)
        self.buttons_layout = QtWidgets.QHBoxLayout()
        self.buttons_layout.setObjectName("buttons_layout")
        self.add_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.add_button.setObjectName("add_button")
        self.buttons_layout.addWidget(self.add_button)
        self.edit_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.edit_button.setObjectName("edit_button")
        self.buttons_layout.addWidget(self.edit_button)
        self.refresh_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.refresh_button.setObjectName("refresh_button")
        self.buttons_layout.addWidget(self.refresh_button)
        self.verticalLayout.addLayout(self.buttons_layout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Каталог кофе"))
        self.title_label.setText(_translate("MainWindow", "Информация о кофе"))
        self.add_button.setText(_translate("MainWindow", "Добавить"))
        self.edit_button.setText(_translate("MainWindow", "Редактировать"))
        self.refresh_button.setText(_translate("MainWindow", "Обновить"))
